### PR TITLE
Migrate to ppxlib >= 0.18.0

### LINKED ISSUE #142: Port ppx_gen_rec to ppxlib
https://github.com/flowtype/ocaml-ppx_gen_rec

### PR DESCRIPTION
**Pull request by giltho**
I'm using flow_parser as a dependency for a JavaScript analysis tool, I'm trying to upgrade ocaml but I need newer versions of ppxs all over. Flow_parser is blocking right now because of ppx_gen_rec.
Not merging this wouldn't be blocking for me, I just thought I'd submit it to help a bit

fixes https://github.com/ocaml-ppx/ppxlib/issues/142

### CODE REVIEW

**Comment by giltho** [comment]
There seem to be an issue when using this with ppx_deriving though..
ppx_deriving has its effect at the same time, it unrolls the [@@deriving show] into `val show...` and ppx_gen_rec raises 
"Psig_value not supported yet".
For now, this can't be used in flow_parser...

**Comment by mroch** [comment]
thanks! i'm on vacation for thanksgiving next week so it'll take a bit to check it out in detail but I skimmed this on my phone. 

this is intended to run before deriving, so that the `[@@deriving show]` in the sig gets copied to the value, and then both are expanded separately. my understanding of `ppxlib` is that it replaces extensions top down, so it's interesting that this doesn't just work.

hopefully there's a way to make ppxlib work. if not, maybe just upgrading ocaml-migrate-parsetree resolves the version constraints you're running into?

alternatively, solving #3 so we don't need this at all could be a last resort

**Comment by mroch** [comment]
#2 fixed this same issue in ocaml-migrate-parsetree, but we don't have the same `position` option in ppxlib

**Comment by giltho** [comment]
No worry ! It gives me a bit of time to think about it. Very busy with coursework marking this week end :/
Thanks for your feedback

**Comment by giltho** [comment]
I must have done something wrong when I tested ppx_gen_rec locally the first time, because I just tested it again and actually there's no conflict with ppx_deriving 🤔 
To make sure of that, I've added the corresponding test and a CI that executes it

**Comment by giltho** [comment]
Hello and Happy new year !

Any update on that side ? Anything I should do differently ?
I'm just checking up on the state of my current PRs, no emergency at all of course.

**Comment by kit-ty-kate** [comment]
Is there any news about this change by any chance?

**Comment by mroch** [comment]
we've been testing this out for a while internally on flow and it seems to work with ppx_deriving. i'll merge!

**Comment by mroch** [comment]
now i have to remember how to do a release 😂

**Comment by giltho** [comment]
Let me know if I can help in any way in publishing / syncing flow with this version :)
I'm quite excited to be able to throw [my fork of flow](https://github.com/giltho/flow) away and use flow_parser directly at the source

**Comment by mroch** [comment]
published v2.0.0! thanks again

**Pull request merged**
